spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mos_burgers
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update

cloudinary:
  cloud-name: dzxiweeoa
  api-key: 397487645729214
  api-secret: PBrD5YQvMj0Dg_TcdVMl7rCTMS4
